# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    assets:
        name: Build and release assets
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v3

            - name: set the release version (tag)
              run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

            - name: Install latest Rust stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  default: true
                  components: clippy, rustfmt

            - name: Install Wasm Rust target
              run: rustup target add wasm32-wasi

            - name: Make
              run: make
              env:
                  RUST_LOG: spin=trace

            - name: generate checksums
              run: |
                  sha256sum target/wasm32-wasi/release/spin_token_auth.wasm > checksums-${{ env.RELEASE_VERSION }}.txt

            - name: Create release
              uses: softprops/action-gh-release@v1
              with:
                  fail_on_unmatched_files: true
                  generate_release_notes: true
                  files: |
                      target/wasm32-wasi/release/spin_token_auth.wasm
                      checksums-${{ env.RELEASE_VERSION }}.txt
